[custom]
;不要随意改变关键字，否则会导致出错
;国内直连 + 国外默认代理 + 全面去广告

; 局域网直连
ruleset=🇨🇳 大陆直连,rules/ACL4SSR/Clash/LocalAreaNetwork.list

; 去广告
ruleset=🔴 广告拦截,rules/ACL4SSR/Clash/BanAD.list
ruleset=🔴 广告拦截,rules/ACL4SSR/Clash/BanProgramAD.list
ruleset=🔴 广告拦截,rules/ACL4SSR/Clash/BanEasyList.list
ruleset=🔴 广告拦截,rules/ACL4SSR/Clash/BanEasyListChina.list
ruleset=🔴 广告拦截,rules/ACL4SSR/Clash/BanEasyPrivacy.list

; 中国大陆直连
ruleset=🇨🇳 大陆直连,rules/ACL4SSR/Clash/ChinaDomain.list
ruleset=🇨🇳 大陆直连,rules/ACL4SSR/Clash/ChinaCompanyIp.list
ruleset=🇨🇳 大陆直连,[]GEOIP,CN

; 其他全部代理
ruleset=🚀 节点选择,[]FINAL

; =========================
; 仅保留 3 个策略组
; =========================

custom_proxy_group=🚀 节点选择`select`.*

custom_proxy_group=🇨🇳 大陆直连`select`[]DIRECT

custom_proxy_group=🔴 广告拦截`select`[]REJECT`[]DIRECT

enable_rule_generator=true
overwrite_original_rules=true
